### ISSUE TITLE
天气插件win10下，每次开机需要重新设置城市

### ISSUE THREAD

**Issue by DeuteriumS** [zhongyang219/TrafficMonitorPlugins#11]
win10下，每次关机后再开机，城市都会恢复默认北京，要看自己这城市需要重新设置。
这个怎么做到保存城市设置。
或者直接根据ip自动跳转城市？

**Comment by zhongyang219** [comment]
这个问题之前有人反馈过，现在应该已经修复了，请确保你使用的TrafficMonitor和插件都是最新版本

**Comment by EwigL** [comment]
我也有这个问题，
TrafficMonitor以及插件都是最新版本。
TrafficMonitor所在目录不需要管理员权限，应该不存在权限问题
![image](https://user-images.githubusercontent.com/43067606/155868256-b985f5f8-74d4-424c-bef4-90e881a9175b.png)

**Comment by EwigL** [comment]
> 
在插件dll同级目录下创建.dll.ini解决了问题。

原先我的设置是
![image](https://user-images.githubusercontent.com/43067606/155872262-0096bc78-0604-4261-b80a-26c08f84476b.png)

改为appdata后发现在appdata目录下程序自动创建了.dll.ini文件，
于是我将配置文件目录改回程序所在目录后，在plugins目录下手动创建了.dll.ini
![image](https://user-images.githubusercontent.com/43067606/155872408-7a593272-3221-4e61-b579-bc39a6b2771c.png)

现在可以保存城市状态了。

**Comment by jyh9521** [comment]
确实，根据楼上的提示发现plugins目录下有一个ini文件，打开看的话里面的城市代码是101，所以每次重启都会变成北京，手动修改成自己当地城市的代码，提权保存即可，应该是Program Files需要管理员权限导致的问题。

**Comment by DeuteriumS** [comment]
之前由于用的是老版本的weather.dll
更新替换新版本之后就解决了这个问题。
