### ISSUE TITLE
大佬来个番茄钟插件吧，愿有偿开发

### ISSUE THREAD

**Issue by Leroy-X** [zhongyang219/TrafficMonitorPlugins#30]
想要一个番茄钟功能，来监督自己的工作。可以任务栏上显示番茄钟状态和剩余时间，可以设置工作时间，休息时间，自动循环，设置提示铃声什么的。。我不懂开发，，就来求救了，感谢开发，撒花！

**Comment by Haojia521** [comment]
看到你的请求正好我也有这个想法，然后写了一个番茄钟插件。可以来这个链接下载[PomodoroTimer](https://github.com/Haojia521/TrafficMonitorPlugins/releases)，使用过程有什么问题和想法可以反馈给我哈。

**Comment by Leroy-X** [comment]
@Haojia521 大佬太帅了，github上的好多番茄钟都是打包的浏览器，动不动一两百Mb。
建议：
1. 数值输入只能点击上下三角或鼠标滚轮，不支持直接数字键入（无妨可以忽略）；
2. 自动循环，最大值限制10次，即5个小时，希望最大值可以99。（建议输入0，则为无限循环）；
3. 可以自定义铃声（比如plugins文件夹下有个sound文件夹啥的，自己的音频文件丢进去，自动添加到提示音下拉列表）；
4. 工作提示音和休息提示音可以单独设定；（无妨可以忽略）；
5. 自动启动复选框，，这样开机就跑番茄钟了；
6. 希望加个休息时屏蔽键盘鼠标的功能，比如休息时冻结键盘鼠标。最好再来个屏幕特效，比如窗口抖动，破碎震裂的效果（去吖的工作，很发泄，或者休息时自动开启屏保也行，嗯嗯）。（https://github.com/wjbgis/Sedentary-reminder, 隔壁家的，画风不好看）
7. 可以实时显示吗，不知道是否更耗性能，类似下图这样精确到秒
![image](https://user-images.githubusercontent.com/13515498/177108394-713e36a6-4c8e-4396-8896-388ed22c9646.png)
9. 目前仅支持中文；

大佬来个捐助二维码吧，非常感谢！！！

**Comment by Haojia521** [comment]
@Leroy-X 根据你的建议更新了部分比较好做的功能，其他功能需要周末有时间了再更新吧。具体更新细节在[发布页面](https://github.com/Haojia521/TrafficMonitorPlugins/releases).
PS：二维码在设置界面~感谢支持哈哈！

**Comment by Leroy-X** [comment]
![image](https://user-images.githubusercontent.com/13515498/177460444-39435ec3-2bd8-4bac-855c-cacc1a96e6ae.png)
当开启**剩余时间显示秒**选项时，重启TrafficMonitor后，**未启动**字样最后一个**动**字会显示不完全，可能是因为秒数字的宽度导致的。

![image](https://user-images.githubusercontent.com/13515498/177461908-93f11d77-6e5c-44d6-bff5-5d5b8493b7c2.png)

然后突然发现西红柿和文字没有水平对齐，不知道是不是为了图标抗锯齿故意这样的。（强迫症。。。）

**Comment by Leroy-X** [comment]
大佬，双击任务栏番茄钟这块区域在开始和暂停之间切换，可以实现吗，会方便很多 :P

**Comment by Haojia521** [comment]
感谢反馈🤝！新版本周三左右会更新。
图标与文字对齐问题，我的win10系统上它们是在竖直方向居中对齐了的。图标和文字绘制是直接调用接口的，可能与系统有关系，不知道你是在用什么系统，和我说一下我这边测试看看。

**Comment by Leroy-X** [comment]
@Haojia521 我这边也是win10，我觉着可能和字体的那个空间尺寸，还是啥有关，不好弄就算了哈（天气的图标好像也是）
大佬，屏蔽键盘鼠标和独立提示音那些别做了吧，感觉太麻烦了。音量也别做了，应该是基于系统的，如果只能比系统小，就没意义了。

建议右键菜单改成，**开始、暂停、跳过、停止和选项**。 默认状态**未启动**改成**停止**。这样统一下，都是两个字符。就不会出现裁切了。
双击在开始和暂停之间切换，这个不知道好实现吗。

然后就很完美了，简介轻便。。。目测是git上最好用的番茄钟了，非常感谢！！！

**Comment by Leroy-X** [comment]
看到更新了，居然还有长时间，简直完美，撒花结束*★,°*:.☆(￣▽￣)/$:*.°★* 。
