### ISSUE TITLE
关于时间与日期插件

### ISSUE THREAD

**Issue by UNSCs117** [zhongyang219/TrafficMonitorPlugins#5]
我按照说明把时间与日期插件(PluginDemo.dll)放进了软件安装目录下的plugins文件夹(也是对应软件x64版本的)，重启软件后插件管理里这个插件的状态是“插件模块加载失败，故障代码193”，并且任务栏中也没有出现时间与日期的显示，而且目录下的error.log也没有记录这个错误。。。

**Comment by UNSCs117** [comment]
[config.txt](https://github.com/zhongyang219/TrafficMonitorPlugins/files/8001588/config.txt)
这个是config.ini，如果有用的话

**Comment by zhongyang219** [comment]
这个问题通常是Trafficmonitor和插件64位/32位版本不匹配导致的，如果你下的是64位插件的话应确保Trafficmonitor也是64位的。通过“帮助”——“关于”对话框可以查看Trafficmonitor的版本。

**Comment by zhongyang219** [comment]
抱歉，是下载链接版本有问题，现在已经修正，请重新下载插件。

**Comment by UNSCs117** [comment]
哦哦没问题了，感谢感谢~
