### ISSUE TITLE
开启系统的使用UTF-8提供全球语言支持功能后天气插件的位置显示乱码。

### ISSUE THREAD

**Issue by shanyan-wcx** [zhongyang219/TrafficMonitorPlugins#80]
![屏幕截图 2023-10-31 110653](https://github.com/zhongyang219/TrafficMonitorPlugins/assets/58252651/dceb0325-fa12-4dbc-9cb4-b0824292aeb9)

**Comment by Haojia521** [comment]
这应该是由于最初插件保存配置文件时用的系统提供的接口，编码格式为ANSI，中文对应GB2312/GBK字符集。系统换用UTF-8后再读取原来的配置文件，就会因为编码不一致导致乱码。解决这个问题可以删除原配置文件，让插件再生成一份新的。

新版插件已经发布，采用了新接口用UTF-8读写配置文件，点击[这里](https://github.com/Haojia521/TrafficMonitorPlugins/releases/tag/weather-pro-v0.10)下载
